image: Visual Studio 2017

version: 0.7.{build}

branches:
    only:
        - master

environment:
    COMPILER: msvc
    VSVER: 14.1

    matrix:
        - QT: C:\Qt\5.12.1\msvc2017_64
          PLATFORM: amd64
          MKSPEC: win64-msvc
        - QT: C:\Qt\5.12.1\msvc2017
          PLATFORM: x86
          MKSPEC: win32-msvc

clone_depth: 1

# scripts that run after cloning repository
install:
    - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;C:\Qt\QtIFW2.0.1\bin\;C:\Program Files\LLVM\bin;%PATH%
    - git submodule update --init --recursive

# scripts that run before build
before_build:
    - if "%MKSPEC%" EQU "win64-msvc" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
    - if "%MKSPEC%" EQU "win64-clang-msvc" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
    - if "%MKSPEC%" EQU "win32-msvc" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat")
    - qmake --version
    - mkdir build
    - cd build
    - if "%MKSPEC%" EQU "win64-msvc" (qmake -r -spec win32-msvc CONFIG+=x86_64 CONFIG-=debug CONFIG+=release ../q5Go.pro)
    - if "%MKSPEC%" EQU "win64-clang-msvc" (qmake -r -spec win32-clang-msvc CONFIG+=x86_64 CONFIG-=debug CONFIG+=release ../q5Go.pro)
    - if "%MKSPEC%" EQU "win32-msvc" (qmake -r -spec win32-msvc CONFIG+=Win32 CONFIG-=debug CONFIG+=release ../q5Go.pro)

# custom build scripts
build_script:
    - jom -j 4

# scripts that run after build
after_build:
    - set q5Go_version=0.7
    - mkdir distrib\q5Go
    - windeployqt.exe --dir .\distrib\q5Go %APPVEYOR_BUILD_FOLDER%\build\src\release\q5go.exe
    - copy "%APPVEYOR_BUILD_FOLDER%\build\src\release\q5go.exe" "distrib\q5Go\q5Go.exe"
    - copy "%APPVEYOR_BUILD_FOLDER%\README.md" "distrib\q5Go\README.md"
    - copy "%APPVEYOR_BUILD_FOLDER%\src\translations\qgo_*.qm" "distrib\q5Go\translations\"
    - copy "%QT%\translations\qt_zh_*.qm" "distrib\q5Go\translations\"
    - echo %q5Go_version% > "distrib\q5Go\version.txt"
    - echo %APPVEYOR_REPO_COMMIT% >> "distrib\q5Go\version.txt"
    - copy "distrib\q5Go\q5Go.exe" "distrib\q5Go_%MKSPEC%.exe"
    - cd distrib
    - 7z a q5Go_%MKSPEC%_portable_%q5Go_version%.zip q5Go

artifacts:
    - path: build\distrib\q5Go_%MKSPEC%_portable_%q5Go_version%.zip
      name: portable
    - path: build\distrib\q5Go_%MKSPEC%.exe
      name: exe_only
